[build]
builder = "nixpacks"

[nixpacks]
python.version = "3.12"

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn habiba_blog.wsgi:application --bind 0.0.0.0:$PORT"
