# Generated by Django - replace the entire content of your 0005_alter_fields_to_cloudinary.py file with this:

from django.db import migrations
import cloudinary.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_convert_to_cloudinary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Main image for the post', null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='blogresource',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, null=True, verbose_name='raw'),
        ),
    ]