# Generated by Django 5.2.5 on 2025-09-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250915_1433'),
        ('blog', '0005_alter_fields_to_cloudinary'),
    ]

    operations = [
    ]
