# Generated by Django 5.2.5 on 2025-09-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_increase_slug_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogview',
            name='referrer',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
